### ISSUE TITLE
 Multiple version of prebuild driver container image support

### ISSUE THREAD

**Issue by chaitanya1731** [kubernetes-sigs/kernel-module-management#161]
### Issue Summary:
KMM Operator should support the multiple versions of pre-built driver container images

### Suggested Priority(P1-P3) & Urgent(Urgent, medium, Low):
P1 & Urgent

### Issue Detail:
As OOT drivers keep upgrading because of feature improvements or any other patches/bug fixes, we need a variable to keep track of such driver module. This comes from the idea mentioned in #114.

### Solution Proposal:
A new variable $MODULE_VERSION need to be introduced into KMM. We can use this variable as a part of image tag to determine the correct mapping of the driver module version to specific kernel version. For ex - 
```
spec:
  moduleVersion: 0.1
...
kernelMappings:
        - regexp: '^.*\.x86_64$'
        containerImage: quay.io/ocpeng/intel-dgpu-driver-container:$MODULE_VERSION-$KERNEL_FULL_VERSION
...
```
