### ISSUE TITLE
Change inTreeModuleToRemove From String To List?

### ISSUE THREAD

**Issue by pjconnol** [kubernetes-sigs/kernel-module-management#458]
Currently for `inTreeModuleToRemove` in the Module CRD, a user can only specify one module (Type: string) which sadly does not cover the case where the In-Tree driver may have other modules depending on it. 

For example with our (Intel) In-Tree ice driver, a user must remove the In-Tree `irdma` driver before removing the In-Tree `ice` driver (`modprobe -r idrma ice`). Failing to do this (Removing In-Tree ice driver only) will result in the error `modprobe: FATAL: Module ice is in use.`

A suggested fix would be for `inTreeModuleToRemove` to accept a list of In-tree modules to remove rather than just one. Then in the order that the user specifies the modules, they will get removed. Example spec:
**Current:**
```yaml
spec:
  moduleLoader:
    container:
      modprobe:
        moduleName: mod_a
        # ...

      # Other fields removed for brevity
      inTreeModuleToRemove: mod_b
```
**Suggested Change:**
```yaml
spec:
  moduleLoader:
    container:
      modprobe:
        moduleName: mod_a
        # ...

      # Other fields removed for brevity
      inTreeModuleToRemove:
         - mod_c
         - mod_b
```

One other alternative that could work is adding an extra flag `inTreeRemoveDependencies: true` which would run `modprobe --remove-dependencies mod_b` in the background. Any solution that suits the community but also allows removal of dependencies on In-Tree drivers works for me!

**Comment by qbarrand** [comment]
Thank you for the issue @pjconnol. Per the `modprobe` manual on my Fedora:
>       -r, --remove
>           This option causes modprobe to remove rather than insert a module.
>           If the modules it depends on are also unused, modprobe will try to
>           remove them too.

I am wondering if setting `inTreeModuleToRemove: irdma` would be enough.

> One other alternative that could work is [...] `modprobe --remove-dependencies mod_b`

Interestingly, this `--remove-dependencies` does not seem to be available on Fedora; however it's listed on `modprobe`'s help on Debian:
```
	    --remove-dependencies   Deprecated: use --remove-holders
	    --remove-holders        Also remove module holders (use together with -r)
```

It's also there when one installs the proper `modprobe` on Alpine (not on the default busybox one).

cc @yevgeny-shnaidman

**Comment by yevgeny-shnaidman** [comment]
@pjconnol i agree with @qbarrand: in case there is a dependency between kernel modules, removing the upmost kernel module should also remove the modules it depends on (unless there are additional reference held by other modules/user-space application). As per modprobe spec:
"_If the modules it depends on are also unused, modprobe will try to remove them to_o"

**Comment by pjconnol** [comment]
@qbarrand @yevgeny-shnaidman Thanks for the responses! I had assumed the Kernel module (ice or i40e in this context) was termed as "in use" if there was an active HW device on the host using it but I think this assumption was wrong. I'll do some quick tests on my test host to see if the following command is useful for installing OOT kernel module: `modprobe -r irdma; modprobe ice`

**Comment by yevgeny-shnaidman** [comment]
@pjconnol please notice that once you do "modprobe -r irdma; modprobe ice", you will load a new version of ice, but you won't have irdma module loaded. This is an interesting use case, i am not sure that KMM by itself can currently deal with it. you would probably need to deploy a second KMM module to load the in-tree irdma driver

**Comment by pjconnol** [comment]
@yevgeny-shnaidman Could the `modulesLoadingOrder` field be hijacked for this, for example:
```yaml
spec:
  moduleLoader:
    container:
      modprobe:
        moduleName: ice
        modulesLoadingOrder:
           - irdma
           - ice
        # ...

      # Other fields removed for brevity
      inTreeModuleToRemove: irdma
```

**Comment by pjconnol** [comment]
@qbarrand @yevgeny-shnaidman Regarding the original issue, this is perfectly resolved by the following Module CR Spec:
```yaml
spec:
  moduleLoader:
    container:
      modprobe:
        moduleName: ice
        # ...

      # Other fields removed for brevity
      inTreeModuleToRemove: irdma
```

**Note:** This was tested using modprobe and not the full KMMO setup
