### ISSUE TITLE
More specific Module Loader targeting than just Linux Kernel Version

### ISSUE THREAD

**Issue by GerrySeidman** [kubernetes-sigs/kernel-module-management#488]
**Issue Summary:**

- Some vendor kernel modules require more specific targeting than just the Linux Kernel Version
  - AuriStor modules are targeted to both Kernel Version, OS Release Version, and OS Distro
    - OS release versions change faster than Kernel release versions
    - There may be heterogeneous nodes in an OpenShift clusters with different OS Release Versions  (exposed from 'uname -a')
  - On other platforms than RHEL/OpenShift ,the Kernel modules are targeted to other distro specific information
    - For example, based on fields that are present in /etc/os-release    
    - See KMM issue #462[](https://github.com/kubernetes-sigs/kernel-module-management/issues/462) 
- Why this should not be addressed with multiple "kernelMapping" entries:
    - Addressing this by extending the level of specificity at .module.spec.moduleLoader.kernelMapping level would be unwieldy due to the the large number of combinations of distro/KernelVersion/releaseVersion. 
    - Addressing the mapping in this manner would also put the burden on the end-user to update the KMM Module with each OS upgrade rather than being automatically picked-up and built by the KMM Module Loaders.
 
**Desired Behavior**
- A new type of "kernelMapping" entry that would allow a single kernelMapping entry to be multi-targeted to nodes based upon combinations Module-provider specified fields (for example 'unname -r' and /etc/os-release fields such as VERSION and VERSION_ID in addition to Linux Kernel Version)
    - The universe of fields could be scoped to those made available through  [NFD Customization](https://kubernetes-sigs.github.io/node-feature-discovery/v0.13/usage/customization-guide.html#node-feature-rule-custom-resource),  perhaps the Module can 'subscribe' to [Available NFD features](https://kubernetes-sigs.github.io/node-feature-discovery/v0.13/usage/customization-guide.html#available-features) 
- These fields would be made made available as Build Arguments to this new single multi-targeted module loader's build script (Dockerfile) which would build the container image corresponding to a combination these subscribed targeting fields.
    - Note: It is unclear how this would map to container image names to be stored in a container registry.  This would need to be further discussed

**Comment by qbarrand** [comment]
> OS release versions change faster than Kernel release versions

Do they? Debian releases a new version approximately every two years.

> Addressing the mapping in this manner would also put the burden on the end-user to update the KMM Module with each OS upgrade rather than being automatically picked-up and built by the KMM Module Loaders.

Does the kernel mapping's `regexp` field solve that issue? It can be used to build a new kmod image each time a new kernel appears in the cluster.

> **Desired Behavior**

Assuming that clusters rarely run different OS releases simultaneously, a workaround that does not require changing the `Module` API is to provide the release name manually in both the `containerImage` field and as a build argument:
```yaml
apiVersion: kmm.sigs.x-k8s.io/v1beta1
kind: Module
metadata:
  name: mymod-debian
spec:
  moduleLoader:
    container:
      modprobe:
        moduleName: mymod
      kernelMappings:
        - regexp: '^.+$'
          containerImage: "some.registry/org/mymod:bullseye-${KERNEL_FULL_VERSION}"
          build:
            buildArgs:
              - name: DEBIAN_RELEASE
                value: bullseye  # or bookworm, or something else...
            dockerfileConfigMap:  # Required
              name: mymod-dockerfile
  selector:
    node-role.kubernetes.io/worker: ""
```
The Dockerfile can then utilize the `DEBIAN_RELEASE` build argument as necessary.
