### ISSUE TITLE
How to not push in-cluster built images?

### ISSUE THREAD

**Issue by mertyildiran** [kubernetes-sigs/kernel-module-management#520]
I have this `Module`:

```yaml
apiVersion: kmm.sigs.x-k8s.io/v1beta1
kind: Module
metadata:
  name: kubeshark-module-loader
spec:
  moduleLoader:
    container:
      modprobe:
        moduleName: pf_ring
        dirName: /opt
      imagePullPolicy: Always
      kernelMappings:
        - regexp: '^.+$'
          containerImage: "kubeshark/module-loader:latest"
          build:
            dockerfileConfigMap:
              name: kubeshark-module-loader-dockerfile
          sign:
            certSecret:
              name: cert-secret
            keySecret:
              name: key-secret
            filesToSign:
              - /opt/lib/modules/5.10.0-23-amd64/pf_ring.ko
  selector:
    beta.kubernetes.io/arch: amd64
```

and the `ConfigMap`:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeshark-module-loader-dockerfile
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubeshark.labels" . | nindent 4 }}
data:
  dockerfile: |
    ### Builder image
    ARG TARGETARCH=amd64
    FROM ${TARGETARCH}/debian:bullseye AS builder

    ARG KERNEL_VERSION

    RUN apt-get update
    RUN apt-get install -y -q \
        curl \
        build-essential \
        linux-headers-${KERNEL_VERSION}

    WORKDIR /work
    RUN curl https://github.com/ntop/PF_RING/archive/refs/tags/8.4.0.tar.gz -Lo ./pfring.tar.xz && \
        tar -xf pfring.tar.xz && \
        mv ./PF_RING-* ./pfring

    WORKDIR /work/pfring/kernel
    ENV KERNELRELEASE=${KERNEL_VERSION}
    RUN make


    ### The shipped image
    ARG TARGETARCH=amd64
    FROM ${TARGETARCH}/debian:bullseye

    ARG KERNEL_VERSION

    RUN apt-get update && apt-get install -y kmod

    COPY --from=builder /work/pfring/kernel/pf_ring.ko /opt/lib/modules/${KERNEL_VERSION}/

    RUN depmod -b /opt ${KERNEL_VERSION}
```

The builder pods print the error message below:

```
error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "kubeshark/module-loader:latest_default_kubeshark-module-loader_kmm_unsigned": creating push check transport for index.docker.io failed: Get "https://index.docker.io/v2/": dial tcp 44.205.64.79:443: connect: connection refused
```

It says `PushBuiltImage` default value is `false` in [here](https://github.com/kubernetes-sigs/kernel-module-management/blob/main/docs/mkdocs/documentation/preflight_validation.md#validation-kick-off). But despite that, it actually tries to push the image into somewhere. I don't know why.

What should I do to disable pushing the images and load the kernel module right away?
