### ISSUE TITLE
The modprobe moduleName only allows one kernel module, rawArgs allows many which is confusing

### ISSUE THREAD

**Issue by cdvultur** [kubernetes-sigs/kernel-module-management#87]
The CRD allows only this kind of format that will insert only one module per CR

```
spec:
  moduleLoader:
    container:
      modprobe:
        moduleName: my-kmod
```

Still while using the rawArgs, multiple modules can be inserted. This is contradictory with the purpose of allowing just one module. 
Also when adding the `rawArgs`, the `moduleName` has to be specified due to the fact that is mandatory, which makes things more confusing.
