### ISSUE TITLE
Modules with a  '.' in their name can not be deleted

### ISSUE THREAD

**Issue by GerrySeidman** [kubernetes-sigs/kernel-module-management#967]
Modules with a  '.' in their name can not be deleted

FAILING Example with module named "test.1"
- Created Module "test.1" with the below YAML
- Deleted Module "test.1"
- KMM properly deletes the kmods on the nodes
- KMM does NOT remove the finalizer from the Module (oc delete module hangs)
    -  The finalizer is never being removed from the module object.
- NOTE: Manually (ie via 'oc edit module' ) removing the finalizer was the only way to delete the module

```
apiVersion: kmm.sigs.x-k8s.io/v1beta1
kind: Module
metadata:
  name: test.1
spec:
  moduleLoader:
    container:
      modprobe:
        moduleName: yfs
      kernelMappings:
        - regexp: '^.+\_4\.x86_64$'
          containerImage: example.com/test-module
```

Working Example with module named "test-1"
- Created Module "test-1" with the below YAML
- Deleted Module "test-1"
- KMM properly deletes the kmods on the nodes
- KMM properly deletes the module

```
apiVersion: kmm.sigs.x-k8s.io/v1beta1
kind: Module
metadata:
  name: test-1
spec:
  moduleLoader:
    container:
      modprobe:
        moduleName: yfs
      kernelMappings:
        - regexp: '^.+\_4\.x86_64$'
          containerImage: example.com/test-module
```

Note: The admission control for other object types (such as Pod) will rejects names containing a '.' in their.  This issue came up for us because a change in our scripting was generating Module's with '.'s in their name.  This would have been caught earlier if the admission controller for modules rejected it upon creation.

Proposed Solutions
- Add this to the admission controller check for Modules  (preferred)
- Properly remove the finalizer for Modules with a '.' in their names
